name: watoplan
description: A simple, yet flexible time management app built with Flutter.

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^3.0.0
  intl: ^0.15.6
  # location: ^1.1.7
  shared_preferences: ^0.4.0
  path_provider: ^0.4.0
  crypto: ^2.0.2
  flutter_local_notifications: ^0.2.2
  flutter_markdown: ^0.1.5
  flutter_calendar: ^0.0.1
  contact_finder:
    path: ../../contact_finder/
    # git:
    #   url: git://github.com/eternali/contact_finder.git
  # location_picker: ^0.0.15
  # sms: ^0.1.0
  # android_alarm_manager: ^0.1.0
  # leveldb: ^5.0.1
  # mongo_dart: ^0.3.1

  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/icons/logo.png
   - assets/defaults/codepoints
   - assets/defaults/data.json
   - assets/defaults/default-avatar.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  fonts:
    - family: Timeburner
      fonts:
        - asset: assets/fonts/timeburner/timeburnernormal.ttf
        - asset: assets/fonts/timeburner/timeburnerbold.ttf
          weight: 700
